### ISSUE TITLE
Try Rector behavior on error

### ISSUE THREAD

**Issue by Hembi** [rectorphp/getrector-com#1439]
# Bug Report
https://getrector.com/demo
If I provide a wrong PHP code to the editor (by mistake while I copy or change it), it returns "Provide a valid PHP code" error message and reset the whole form to default. I have to start the whole process again.

## Expected Behaviour
Provide error message and keep the changes in textareas.

**Comment by TomasVotruba** [comment]
As stated in other repo, feel free to provide a PR with suggested improvement :+1: 

The code is fully open-source and any giving back is welcomed.
