### ISSUE TITLE
Setup bladestan?

### ISSUE THREAD

**Issue by staabm** [rectorphp/getrector-com#1644]
I am looking for bladestan use-cases to measure for perf bottlenecks.

i don‘t have any laravel project, so maybe we can use this one?
Alternatively maybe someone can give me access to a project which uses bladestan extensively, so I can do some measuring…?

**Comment by TomasVotruba** [comment]
Hi, I'm going through forgotten issues and questions :)

I personally don't have any big Laravel-template project to provide. I think it would have to be a private one, as that's the best source of any dirt :)
