### ISSUE TITLE
missing "create test" or "create issue" button

### ISSUE THREAD

**Issue by staabm** [rectorphp/getrector-com#1740]
it seems the website no longer shows the "create issue" or "create test" buttons?

see e.g. https://getrector.com/demo/b2fd9fbe-1209-4cbb-a317-fdd49ad2f2b1

**Comment by TomasVotruba** [comment]
Those only show when there is issue and single responsible rule. The reason the tests will be added to particular rule.

**Comment by TomasVotruba** [comment]
See: https://github.com/rectorphp/getrector-com/blob/ab8c730d3d347f27770ff26d36f15029e67e93e6/resources/views/demo/demo.blade.php#L84

https://github.com/rectorphp/getrector-com/blob/ab8c730d3d347f27770ff26d36f15029e67e93e6/src/Entity/RectorRun.php#L160-L163
