### ISSUE TITLE
GitHub Actions Cache key

### ISSUE THREAD

**Issue by SomeBdyElse** [rectorphp/getrector-com#2022]
The current documentation suggests to use the following cache key for GitHub actions: 

```
${{ runner.os }}-rector-${{ hashFiles('**/composer.lock') }}
```

https://github.com/rectorphp/getrector-com/blob/be17729dedb91d48dbe6a904ba3f84bed391d28d/resources/docs/cache-in-ci.md?plain=1#L42

GHA caches are immutable. Therefore the cache will be stored once and updated only if the composer.lock changes. I do believe that the cache contents are dependent on non-vendor php files which might changes without alterations to the composer.lock. Therefore the cache should also be updated without changes to the composer.lock. 

I suggest to change the cache key to: 
```
rector-${{ hashFiles('**/composer.lock') }}-${{ github.run_id }}
```

The pattern is suggested here: https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache

**Comment by staabm** [comment]
we usually use something like

```
key: ${{ steps.setup-php.outputs.php-version }}-rector-${{ github.run_id }}
restore-keys: ${{ steps.setup-php.outputs.php-version }}-rector- 
```

`${{ hashFiles('**/composer.lock') }}` is not really useful, I agree.

**Comment by samsonasik** [comment]
I am not familiar with it, could you guys try create a PR for it? Thank you.

**Comment by staabm** [comment]
just sent https://github.com/rectorphp/getrector-com/pull/2023

@SomeBdyElse could you double check it?
