### ISSUE TITLE
improve "find rule" search

### ISSUE THREAD

**Issue by staabm** [rectorphp/getrector-com#2685]
searching for words like "Parameter" should also find rules like e.g.

``` 
ExplicitNullableParamTypeRector
RemoveMethodCallParamRector 
```

**Comment by staabm** [comment]
I also wonder why `AddMethodCallBasedStrictParamTypeRector` is not found at all when searching for "param"

**Comment by TomasVotruba** [comment]
Feel free to send PRs for these directly, as real implementation can lead many  ways 👍
